/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2017-05-06 11:51:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class employee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>employee_regis</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("*, *:before, *:after {\n");
      out.write("\t-moz-box-sizing: border-box;\n");
      out.write("\t-webkit-box-sizing: border-box;\n");
      out.write("\tbox-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\tfont-family: 'Nunito', sans-serif;\n");
      out.write("\tcolor: #384047;\n");
      out.write("}\n");
      out.write("\n");
      out.write("form {\n");
      out.write("\tmax-width: 300px;\n");
      out.write("\tmargin: 10px auto;\n");
      out.write("\tpadding: 10px 20px;\n");
      out.write("\tbackground: #f4f7f8;\n");
      out.write("\tborder-radius: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h1 {\n");
      out.write("\tmargin: 0 0 30px 0;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"text\"], input[type=\"password\"], input[type=\"date\"], input[type=\"datetime\"],\n");
      out.write("\tinput[type=\"email\"], input[type=\"number\"], input[type=\"search\"], input[type=\"tel\"],\n");
      out.write("\tinput[type=\"time\"], input[type=\"url\"], textarea, select {\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.1);\n");
      out.write("\tborder: none;\n");
      out.write("\tfont-size: 16px;\n");
      out.write("\theight: auto;\n");
      out.write("\tmargin: 0;\n");
      out.write("\toutline: 0;\n");
      out.write("\tpadding: 15px;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tbackground-color: #e8eeef;\n");
      out.write("\tcolor: #8a97a0;\n");
      out.write("\tbox-shadow: 0 1px 0 rgba(0, 0, 0, 0.03) inset;\n");
      out.write("\tmargin-bottom: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"radio\"], input[type=\"checkbox\"] {\n");
      out.write("\tmargin: 0 4px 8px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("select {\n");
      out.write("\tpadding: 6px;\n");
      out.write("\theight: 32px;\n");
      out.write("\tborder-radius: 2px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button {\n");
      out.write("\tpadding: 19px 39px 18px 39px;\n");
      out.write("\tcolor: #FFF;\n");
      out.write("\tbackground-color: #4bc970;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tfont-style: normal;\n");
      out.write("\tborder-radius: 5px;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tborder: 1px solid #3ac162;\n");
      out.write("\tborder-width: 1px 1px 3px;\n");
      out.write("\tbox-shadow: 0 -1px 0 rgba(255, 255, 255, 0.1) inset;\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("fieldset {\n");
      out.write("\tmargin-bottom: 30px;\n");
      out.write("\tborder: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("legend {\n");
      out.write("\tfont-size: 1.4em;\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("label {\n");
      out.write("\tdisplay: block;\n");
      out.write("\tmargin-bottom: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("label.light {\n");
      out.write("\tfont-weight: 300;\n");
      out.write("\tdisplay: inline;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (min-width: 480px) {\n");
      out.write("\tform {\n");
      out.write("\t\tmax-width: 480px;\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function employeeValidate(){\n");
      out.write("\tvar name = document.getElementByName(\"uname\").value;\n");
      out.write("\tvar addr = document.getElementByName(\"addr\").value;\n");
      out.write("\tvar cmp = document.getElementByName(\"cmp\").value;\n");
      out.write("\tvar age = document.getElementByName(\"age\").value;\n");
      out.write("\tvar gender = document.getElementByName(\"gender\").value;\n");
      out.write("\tvar domain = document.getElementByName(\"domain\").value;\n");
      out.write("\tvar lang = document.getElementByName(\"lang\").value;\n");
      out.write("\tvar x=document.getElementById(\"mail\").value;\n");
      out.write("\tvar atposition=x.indexOf(\"@\");  \n");
      out.write("\tvar dotposition=x.lastIndexOf(\".\");  \n");
      out.write("\t\n");
      out.write("\tif (atposition<1 || dotposition<atposition+2 || dotposition+2>=x.length){  \n");
      out.write("\t\t  alert(\"Please enter a valid e-mail address\");  \n");
      out.write("\t\t  return false;  \n");
      out.write("\t\t  }\n");
      out.write("\tif(name.length==null||name==\" \"||name.length<=3)\n");
      out.write("\t{\n");
      out.write("\talert(\"Enter name\");\n");
      out.write("\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif(addr.length==null || addr.length==\" \"){\n");
      out.write("\t\talert(\"Address can't be empty !!\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif(cmp.length==null || cmp.length==\" \"){\n");
      out.write("\t\talert(\"Company can't be empty !!\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif(age.length==null || age.length==\" \" && age==[a-z]){\n");
      out.write("\t\talert(\"Age can't be empty  !!\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t\t/* if(age==[a-z]){\n");
      out.write("\t\t\talert(\"Age Must Be a Number !!\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t} */\n");
      out.write("\t}\n");
      out.write("\tif(gender.length==null || gender.length==\" \"){\n");
      out.write("\t\talert(\"Gender can't be empty !!\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif(domain.length==None || domain.length==\" \"){\n");
      out.write("\t\talert(\"Choose Any Technology !!\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif(lang.length==None || lang.length==\" \"){\n");
      out.write("\t\talert(\"Company can't be empty !!\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\treturn true;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<div align=\"right\">\n");
      out.write("\t<a href=\"employeeDetails\">Employee Details</a>\n");
      out.write("\t<a href=\"logoutServlet\">Logout</a>\n");
      out.write("</div>\n");
      out.write("<body>\n");
      out.write("\t<form action=\"employeeRegister\" method=\"post\"\n");
      out.write("\t\tonsubmit=\"return employeeValidate()\">\n");
      out.write("\n");
      out.write("\t\t<h1>Sign Up</h1>\n");
      out.write("\n");
      out.write("\t\t<fieldset>\n");
      out.write("\t\t\t<label for=\"name\">Name:</label> <input type=\"text\" name=\"uname\"\n");
      out.write("\t\t\t\tid=\"name\"> <label for=\"mail\">Email:</label> <input\n");
      out.write("\t\t\t\ttype=\"email\" id=\"mail\" name=\"mail\"> <label for=\"password\">Company:</label>\n");
      out.write("\t\t\t<input type=\"text\" name=\"company\" id=\"cmp\"> <label>Age:</label>\n");
      out.write("\t\t\t<input type=\"text\" id=\"age\" name=\"age\"> <label>Gender:</label>\n");
      out.write("\t\t\t<input type=\"radio\" id=\"gender\" value=\"male\" name=\"gender\"><label\n");
      out.write("\t\t\t\tfor=\"under_13\" class=\"light\"> Male</label><br> <input\n");
      out.write("\t\t\t\ttype=\"radio\" id=\"gender\" value=\"female\" name=\"gender\"><label\n");
      out.write("\t\t\t\tfor=\"over_13\" class=\"light\">Female</label>\n");
      out.write("\n");
      out.write("\t\t</fieldset>\n");
      out.write("\t\t<fieldset>\n");
      out.write("\n");
      out.write("\t\t\t<label for=\"bio\">Address:</label>\n");
      out.write("\t\t\t<textarea name=\"address\" id=\"addr\"></textarea>\n");
      out.write("\n");
      out.write("\t\t</fieldset>\n");
      out.write("\t\t<fieldset>\n");
      out.write("\n");
      out.write("\t\t\t<label for=\"job\">Specialized Technology:</label> <select\n");
      out.write("\t\t\t\tname=\"specialized\" id=\"domain\">\n");
      out.write("\t\t\t\t<optgroup label=\"Web\">\n");
      out.write("\t\t\t\t\t<option value=\"html\">HTML</option>\n");
      out.write("\t\t\t\t\t<option value=\"php_developor\">PHP</option>\n");
      out.write("\t\t\t\t\t<option value=\"python_developer\">Python</option>\n");
      out.write("\t\t\t\t\t<option value=\"rails_developer\">Rails</option>\n");
      out.write("\t\t\t\t\t<option value=\"web_designer\">Web Designer</option>\n");
      out.write("\t\t\t\t\t<option value=\"WordPress_developer\">WordPress Developer</option>\n");
      out.write("\t\t\t\t</optgroup>\n");
      out.write("\t\t\t\t<optgroup label=\"Mobile\">\n");
      out.write("\t\t\t\t\t<option value=\"Android_developer\">Androild</option>\n");
      out.write("\t\t\t\t\t<option value=\"iOS_developer\">iOS</option>\n");
      out.write("\t\t\t\t\t<option value=\"mobile_designer\">Phone Gap</option>\n");
      out.write("\t\t\t\t</optgroup>\n");
      out.write("\t\t\t\t<optgroup label=\"Core_Tech\">\n");
      out.write("\t\t\t\t\t<option value=\"C\">C</option>\n");
      out.write("\t\t\t\t\t<option value=\"C++\">C++</option>\n");
      out.write("\t\t\t\t\t<option value=\"Java\">Java</option>\n");
      out.write("\t\t\t\t\t<option value=\".Net\">.Net</option>\n");
      out.write("\t\t\t\t</optgroup>\n");
      out.write("\t\t\t</select> <label for=\"job\">Languages:</label> <select name=\"language\"\n");
      out.write("\t\t\t\tid=\"lang\">\n");
      out.write("\t\t\t\t<option value=\"hindi\">Hindi</option>\n");
      out.write("\t\t\t\t<option value=\"english\">English</option>\n");
      out.write("\t\t\t\t<option value=\"Marathi\">Marathi</option>\n");
      out.write("\t\t\t\t<option value=\"Punjabi\">Punjabi</option>\n");
      out.write("\t\t\t\t<option value=\"Telgu\">Telgu</option>\n");
      out.write("\t\t\t\t<option value=\"Tamil\">Tamil</option>\n");
      out.write("\t\t\t\t<option value=\"Bengali\">Bengali</option>\n");
      out.write("\t\t\t\t<option value=\"Oria\">Oria</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\n");
      out.write("\t\t\t<!-- <label>Interests:</label>\n");
      out.write("          <input type=\"checkbox\" id=\"development\" value=\"interest_development\" name=\"user_interest\"><label class=\"light\" for=\"development\">Development</label><br>\n");
      out.write("          <input type=\"checkbox\" id=\"design\" value=\"interest_design\" name=\"user_interest\"><label class=\"light\" for=\"design\">Design</label><br>\n");
      out.write("          <input type=\"checkbox\" id=\"business\" value=\"interest_business\" name=\"user_interest\"><label class=\"light\" for=\"business\">Business</label> -->\n");
      out.write("\t\t</fieldset>\n");
      out.write("\t\t<button type=\"submit\">Sign Up</button>\n");
      out.write("\t</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
