/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2017-05-06 11:51:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("@import url(https://fonts.googleapis.com/css?family=Roboto:300);\n");
      out.write("\n");
      out.write(".login-page {\n");
      out.write("\twidth: 360px;\n");
      out.write("\tpadding: 8% 0 0;\n");
      out.write("\tmargin: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form {\n");
      out.write("\tposition: relative;\n");
      out.write("\tz-index: 1;\n");
      out.write("\tbackground: #FFFFFF;\n");
      out.write("\tmax-width: 360px;\n");
      out.write("\tmargin: 0 auto 100px;\n");
      out.write("\tpadding: 45px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tbox-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0\n");
      out.write("\t\trgba(0, 0, 0, 0.24);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form input {\n");
      out.write("\tfont-family: \"Roboto\", sans-serif;\n");
      out.write("\toutline: 0;\n");
      out.write("\tbackground: #f2f2f2;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tborder: 0;\n");
      out.write("\tmargin: 0 0 15px;\n");
      out.write("\tpadding: 15px;\n");
      out.write("\tbox-sizing: border-box;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form button {\n");
      out.write("\tfont-family: \"Roboto\", sans-serif;\n");
      out.write("\ttext-transform: uppercase;\n");
      out.write("\toutline: 0;\n");
      out.write("\tbackground: #4CAF50;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tborder: 0;\n");
      out.write("\tpadding: 15px;\n");
      out.write("\tcolor: #FFFFFF;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\t-webkit-transition: all 0.3 ease;\n");
      out.write("\ttransition: all 0.3 ease;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form button:hover, .form button:active, .form button:focus {\n");
      out.write("\tbackground: #43A047;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form .message {\n");
      out.write("\tmargin: 15px 0 0;\n");
      out.write("\tcolor: #b3b3b3;\n");
      out.write("\tfont-size: 12px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form .message a {\n");
      out.write("\tcolor: #4CAF50;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form .register-form {\n");
      out.write("\tdisplay: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("\tposition: relative;\n");
      out.write("\tz-index: 1;\n");
      out.write("\tmax-width: 300px;\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container:before, .container:after {\n");
      out.write("\tcontent: \"\";\n");
      out.write("\tdisplay: block;\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container .info {\n");
      out.write("\tmargin: 50px auto;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container .info h1 {\n");
      out.write("\tmargin: 0 0 15px;\n");
      out.write("\tpadding: 0;\n");
      out.write("\tfont-size: 36px;\n");
      out.write("\tfont-weight: 300;\n");
      out.write("\tcolor: #1a1a1a;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container .info span {\n");
      out.write("\tcolor: #4d4d4d;\n");
      out.write("\tfont-size: 12px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container .info span a {\n");
      out.write("\tcolor: #000000;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container .info span .fa {\n");
      out.write("\tcolor: #EF3B3A;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".div {\n");
      out.write("\theight: 75px;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tbackground-color: gray;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function userReg()\n");
      out.write("{\n");
      out.write("\tvar name=document.getElementById(\"uname\").value;\n");
      out.write("\tvar userid=document.getElementById(\"uid\").value;\n");
      out.write("\tvar pass=document.getElementById(\"pwd1\").value;\n");
      out.write("\tvar x=document.getElementById(\"mailid\").value;\n");
      out.write("\tvar atposition=x.indexOf(\"@\");  \n");
      out.write("\tvar dotposition=x.lastIndexOf(\".\");  \n");
      out.write("\t\n");
      out.write("\tconsole.log(pass);\n");
      out.write("\t\n");
      out.write("\tif (atposition<1 || dotposition<atposition+2 || dotposition+2>=x.length){  \n");
      out.write("\t\t  alert(\"Please enter a valid e-mail address \\n atpostion:\"+atposition+\"\\n dotposition:\"+dotposition);  \n");
      out.write("\t\t  return false;  \n");
      out.write("\t\t  }  \n");
      out.write("\t\n");
      out.write("\tif(name.length==null||name==\" \"||name.length<=3)\n");
      out.write("\t\t{\n");
      out.write("\t\talert(\"Enter name\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\tif(userid.length==null||userid==\" \"||userid.length<3 || userid==[a-z])\n");
      out.write("\t{\n");
      out.write("\talert(\"Enter User ID\");\n");
      out.write("\treturn false;\n");
      out.write("\t}\n");
      out.write("\tif(pass.length==null||pass==\" \"||pass.length<=3)\n");
      out.write("\t{\n");
      out.write("\talert(\"Enter Password\");\n");
      out.write("\treturn false;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\telse\n");
      out.write("\t\t{\n");
      out.write("\t\treturn true;\n");
      out.write("\t\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<body bgcolor=\"white\">\n");
      out.write("\t<div class=\"div\"></div>\n");
      out.write("\t<div class=\"login-page\">\n");
      out.write("\t\t<div class=\"form\">\n");
      out.write("\n");
      out.write("\t\t\t<h3>User Register Page</h3>\n");
      out.write("\t\t\t<form class=\"login-form\" action=\"userreg\" method=\"post\"\n");
      out.write("\t\t\t\tonsubmit=\"return userReg()\">\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"uid\" id=\"uid\" placeholder=\"userid\" /> <input\n");
      out.write("\t\t\t\t\ttype=\"text\" name=\"user\" id=\"uname\" placeholder=\"username\" /> <input\n");
      out.write("\t\t\t\t\ttype=\"text\" name=\"mail\" id=\"mailid\" placeholder=\"email_id\" /> <input\n");
      out.write("\t\t\t\t\ttype=\"password\" name=\"pwd\" id=\"pwd1\" placeholder=\"password\" />\n");
      out.write("\t\t\t\t<button>register</button>\n");
      out.write("\t\t\t\t<p class=\"message\">\n");
      out.write("\t\t\t\t\tAlready registered? <a href=\"userlogin.jsp\">Sign In</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
